export VISUAL=nvim;
export EDITOR=nvim;
export MANPAGER="less -R --use-color -Dd+r -Du+b"

alias v=$EDITOR
alias grep='grep --color=auto -i'
alias ls='ls --color=auto'
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias df="df -h"
alias free="free -mh"
alias his='history | fzf'
